# ─── AUTH SERVICE ───────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: auth
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOjgxTjYlMkFtak8lMkFuazU3diU1REhEJTdDJTNFS2FUSmw1cW1nQGF1dGgtc2VydmljZS5jdGl1aTdxbHVxaTkudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvcG9zdGdyZXM=
  DB_HOST: YXV0aC1zZXJ2aWNlLmN0aXVpN3FsdXFpOS51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
  DB_USER: cG9zdGdyZXM=
  DB_PASS: ODFONiptak8qbms1N3ZdSER8PkthVEpsNXFtZw==
  JWT_SECRET: dG1fa2V5X2JiNDZhYzA4YTBhNGNjZTgwOTIyODQ1MmFiYTE4MjM1YTBiNWRiZDczOTFhN2NiM2YxYzY0OTljNTQwOWMzMmQ=
  MASTER_KEY: dG1fa2V5X2JiNDZhYzA4YTBhNGNjZTgwOTIyODQ1MmFiYTE4MjM1YTBiNWRiZDczOTFhN2NiM2YxYzY0OTljNTQwOWMzMmQ=
---
# ─── FLAG SERVICE ────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secret
  namespace: flags
type: Opaque
data:
  DB_HOST: ZmxhZy1zZXJ2aWNlLmN0aXVpN3FsdXFpOS51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
  DB_USER: cG9zdGdyZXM=
  DB_PASS: Q19UJHwkd2NvNDAkMW9DQUJKc1lWRzZNUlBEQg==
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOkNfVCUyNCU3QyUyNHdjbzQwJTI0MW9DQUJKc1lWRzZNUlBEQkBmbGFnLXNlcnZpY2UuY3RpdWk3cWx1cWk5LnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL3Bvc3RncmVz
---
# ─── TARGETING SERVICE ───────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
  namespace: targeting
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOiU1QkdsSWZLTzMlMjE3JTVEbXBPT2wlMjlRYkJ+XyUyOXNxSVVDQHRhcmdldGluZy1zZXJ2aWNlLmN0aXVpN3FsdXFpOS51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi9wb3N0Z3Jlcw==
  DB_HOST: dGFyZ2V0aW5nLXNlcnZpY2UuY3RpdWk3cWx1cWk5LnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  DB_USER: cG9zdGdyZXM=
  DB_PASS: W0dsSWZLTzMhN11tcE9PbClRYkJ+XylzcUlVQw==
  AWS_ACCESS_KEY_ID: QVNJQTNOMlVQRUpFWTNYQjdQM1M=
  AWS_SECRET_ACCESS_KEY: YktXTHIvcVNmTHR0YkNJNzZrZ0RhalpxaEhsTnZNbXlOVEJlU29reQ==
  AWS_SESSION_TOKEN: SVFvSmIzSnBaMmx1WDJWakVLUC8vLy8vLy8vLy93RWFDWFZ6TFhkbGMzUXRNaUpJTUVZQ0lRRERmUWdyRU00c1ZwbzBFS294enhIU0drWXBUL2VZV1ZWRTNiR0wzRFN1VkFJaEFJd1VaTks2aWdpSVZoazhpTk1taEVpU3R6UDJvNTFJZUxMN2hGN3hLaGdMS3FzQ0NHd1FBaG9NTnpnMU5qRTVNamsyT0RReElnemEvQld1UWdUMDlET0t1SllxaUFMYUs0OFY0eUhpOXptRXZNVmRUUEZjdUwremlCazI0WjZFd0hoOTE3SDZBUmVzUDVDMnVQR1ZsZXU1RVJjMjBBVEZXSi8rWjZ4djI5RGZKc0RwU1B6NTFkS255N1JSYlpUd1ZTbnk0bEh6MFhJeU9PV1FXVmRyS1Vnd0M5ZCtCaUp0amVPS0NSekVMQUg3dFFtQ0xDNDJvanlWN3ZwWWFJSmZCNGtxaWhtVFJuRHdkV09CT2pPTFBIZmxCQllZN1VISHdweWZqRGo2VVhRdVlLMmVyNmhyeHVyNjFmdm5mYU5DdExQNE5WV0ZBanlkYmZvbVJxZzM0WkNDL2xjckxjaGJoelhlVzFlUUt2N0VWY2ZRclFDVXpmNzZNUTFheUpMcHYvWkJiaXVxM2xpQ1VIbjFOTW5XS290bUNEY285c204YVVuUkt6eXdFY1Z2eWhLd3VYRW5WZnFNVGtiWHFxZ3d1TlBNMUFZNm5BR29nb0lGRUxIVjM1VlkzTktqRUNmRTcwYnExdEJadTc1R3l5MHljODJXYTVQUTU1MHBvU0tkcGxnQ2xveXNQOTA4alVvaElQWjFBdmZzV1d4UnJFWWsvZ1BUZXJjd25mbTlUMmFrMHFwRVk5c2J5WjA1c0phM0I2ZlNuMy9xVzFVTHgwYXcrTTVUOVlHU3ZGcThZOW1QVEpsaEpEYVI0ckV3aGhRSVBKYVBIZTZrcTJNd1B6bkVsZlYvTHEzYm8xVXhLb2dxT3JWTGVHNjFhNms9
---
# ─── EVALUATION SERVICE ──────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: evaluation
type: Opaque
data:
  REDIS_URL: cmVkaXNzOi8vZXZhbHVhdGlvbi1zZXJ2aWNlLTZmbGlpYS5zZXJ2ZXJsZXNzLnVzZTEuY2FjaGUuYW1hem9uYXdzLmNvbTo2Mzgw
---
# ─── ANALYTICS SERVICE ───────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: analytics
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QVNJQTNOMlVQRUpFWTNYQjdQM1M=
  AWS_SECRET_ACCESS_KEY: YktXTHIvcVNmTHR0YkNJNzZrZ0RhalpxaEhsTnZNbXlOVEJlU29reQ==
  AWS_SESSION_TOKEN: SVFvSmIzSnBaMmx1WDJWakVLUC8vLy8vLy8vLy93RWFDWFZ6TFhkbGMzUXRNaUpJTUVZQ0lRRERmUWdyRU00c1ZwbzBFS294enhIU0drWXBUL2VZV1ZWRTNiR0wzRFN1VkFJaEFJd1VaTks2aWdpSVZoazhpTk1taEVpU3R6UDJvNTFJZUxMN2hGN3hLaGdMS3FzQ0NHd1FBaG9NTnpnMU5qRTVNamsyT0RReElnemEvQld1UWdUMDlET0t1SllxaUFMYUs0OFY0eUhpOXptRXZNVmRUUEZjdUwremlCazI0WjZFd0hoOTE3SDZBUmVzUDVDMnVQR1ZsZXU1RVJjMjBBVEZXSi8rWjZ4djI5RGZKc0RwU1B6NTFkS255N1JSYlpUd1ZTbnk0bEh6MFhJeU9PV1FXVmRyS1Vnd0M5ZCtCaUp0amVPS0NSekVMQUg3dFFtQ0xDNDJvanlWN3ZwWWFJSmZCNGtxaWhtVFJuRHdkV09CT2pPTFBIZmxCQllZN1VISHdweWZqRGo2VVhRdVlLMmVyNmhyeHVyNjFmdm5mYU5DdExQNE5WV0ZBanlkYmZvbVJxZzM0WkNDL2xjckxjaGJoelhlVzFlUUt2N0VWY2ZRclFDVXpmNzZNUTFheUpMcHYvWkJiaXVxM2xpQ1VIbjFOTW5XS290bUNEY285c204YVVuUkt6eXdFY1Z2eWhLd3VYRW5WZnFNVGtiWHFxZ3d1TlBNMUFZNm5BR29nb0lGRUxIVjM1VlkzTktqRUNmRTcwYnExdEJadTc1R3l5MHljODJXYTVQUTU1MHBvU0tkcGxnQ2xveXNQOTA4alVvaElQWjFBdmZzV1d4UnJFWWsvZ1BUZXJjd25mbTlUMmFrMHFwRVk5c2J5WjA1c0phM0I2ZlNuMy9xVzFVTHgwYXcrTTVUOVlHU3ZGcThZOW1QVEpsaEpEYVI0ckV3aGhRSVBKYVBIZTZrcTJNd1B6bkVsZlYvTHEzYm8xVXhLb2dxT3JWTGVHNjFhNms9
  AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vNzg1NjE5Mjk2ODQxL3RvZ2dsZS1tYXN0ZXItZXZlbnRz
